spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hr
    username: hr
    password: hr
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: INFO
    vnedraid.inputservice: DEBUG
    reactor.netty.http.client: DEBUG

hh:
  delay:
    ms: 300000                # 5
  monitoring:
    requests:
      - text: "Java developer"
        area: 1