server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://db:5432/hr
    username: hr
    password: hr
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

cors:
  allowed-origins: "http://localhost:3000"
