services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: hr
      POSTGRES_USER: hr
      POSTGRES_PASSWORD: hr
    ports: ["5432:5432"]

  input-service:
    build:
      context: ./InputService
      dockerfile: Dockerfile
    depends_on: [ db ]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hr
      SPRING_DATASOURCE_USERNAME: hr
      SPRING_DATASOURCE_PASSWORD: hr
    ports: ["8080:8080"]

  api-service:
    build:
      context: ./ApiService
      dockerfile: Dockerfile
    depends_on: [ db ]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hr
      SPRING_DATASOURCE_USERNAME: hr
      SPRING_DATASOURCE_PASSWORD: hr
    ports: [ "8081:8081" ]
