# Используем только рантайм-слой JDK 21
FROM eclipse-temurin:21-jre AS runtime
WORKDIR /app

# Копируем предварительно собранный jar
COPY InputService-*.jar app.jar

# (опционально) выставляем лимиты JVM
ENV JAVA_OPTS="-Xms256m -Xmx512m"

EXPOSE 8080
ENTRYPOINT ["sh","-c","java $JAVA_OPTS -jar /app/app.jar"]
